spring:
  application:
    name: mykingdom-imking
  datasource:
    url: jdbc:mysql://192.168.0.118:3306/imking?useSSL=false&useUnicode=true&characterEncoding=UTF8
    driver-class-name: com.mysql.jdbc.Driver
    username: imking
    password: 46OMuh4j
    druid:
      initial-size: 10
      max-active: 20
      min-idle: 10
      max-wait: 10
    schema: classpath:create-db.sql
    data: classpath:demo-data.sql
    initialize: true
    continue-on-error: true
  redis:
    host: 192.168.0.3
    port: 6379
    password:

server:
  port: 8080
  context-path: /
  tomcat:
    uri-encoding: UTF-8

logging:
  config: classpath:log4j2.xml

mybatis:
  configuration:
    cache-enabled: false
    aggressive-lazy-loading: false
    use-generated-keys: false
    auto-mapping-behavior: partial
    default-executor-type: reuse
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    local-cache-scope: statement
#  type-handlers-package: